version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
    environment:
      - DEBUG=True
    restart: always

volumes:
  sqlite_data:
